name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          # Use uv to sync the virtual environment and install dev dependencies
          uv venv
          uv pip install -e ".[dev]"
        shell: bash

      - name: Run tests with coverage
        run: |
          # Use uv run to execute pytest from the virtual environment
          # The --cov setting specifies which package to measure coverage for.
          uv run pytest --cov=openwebui --cov-report=xml
        shell: bash

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5.5.0
        with:
          file: ./coverage.xml